// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuwefqlgkkgijpeyncdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1d2VmcWxna2tnaWpwZXluY2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTk0OTYsImV4cCI6MjA3MDk3NTQ5Nn0.ZczXLbWvEgLXO1nzjvGCPE7spqycpbiZNS7pgMNHpwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});